In [1]:
##### Using Measurements to Calcuate Error in Local Clock Time for Nodes #####

####################
# IMPORT LIBRARIES #
####################

import numpy as np
from colorama import Fore, Style

In [2]:
####################
# DEFINE FUNCTIONS #
####################

def find_e_vector(col_num, links):
    file_name = "col_" + str(col_num) + ".txt"
    d = 0
    delta = np.zeros((len(links),1))

    with open(file_name,'r') as f:
        vals = f.readlines()
    
    for val in vals:
        val = val.replace(",\n", "")
        delta[d] = (int(val))
        d += 1
    
    estimate = np.dot(pinvA, delta)

    e_est = estimate[:len(rx_names)]
    T_est = estimate[len(rx_names):]
    return e_est, T_est

def print_results(col_num, rx_names, e_est, T_est):
    print(" ---------- column (repNum) " + str(col_num) + " in delta.txt ---------- ")
    print(Fore.RED + "(~, rx_name ) -----    e_estimate    -----   T_estimate" + Style.RESET_ALL)
    r = 0

    for rx in rx_names:
        rx_temp = rx
        if len(rx) != len("browning"):
            for i in range(len("browning")-len(rx)):
                rx_temp += " "
        if e_est[r][0] < 0 or T_est[r][0] < 0:
            print("(~, " + rx_temp + ") -----  [" + format(e_est[r][0],'.7f') + "]  ----- [" + 
                  format(T_est[r][0],'.7f') + ']')
        else:
            print("(~, " + rx_temp + ") -----  [" + format(e_est[r][0],'.8f') + "]  ----- [" + 
                  format(T_est[r][0],'.8f') + ']')
        r += 1

In [3]:
####################
# SETTING UP LINKS #
####################

rx_names = ["bes","browning","fm","honors","hospital","smt","ustar"]
links_names = ["bes-browning","bes-fm","bes-honors","bes-hospital","bes-smt","bes-ustar",
         "browning-bes","browning-fm","browning-honors","browning-hospital","browning-smt","browning-ustar",
         "fm-bes","fm-browning","fm-honors","fm-hospital","fm-smt","fm-ustar",
         "honors-bes","honors-browning","honors-fm","honors-hospital","honors-smt","honors-ustar",
         "hospital-bes","hospital-browning","hospital-fm","hospital-honors","hospital-smt","hospital-ustar",
         "smt-bes","smt-browning","smt-fm","smt-honors","smt-hospital","smt-ustar",
         "ustar-bes","ustar-browning","ustar-fm","ustar-honors","ustar-hospital","ustar-smt"]
links = []

for pair in links_names:
    pair = pair.split("-")
    links.append(pair)
    # print(pair)

print(" ----- all node links ----- ")
print(links)

 ----- all node links ----- 
[['bes', 'browning'], ['bes', 'fm'], ['bes', 'honors'], ['bes', 'hospital'], ['bes', 'smt'], ['bes', 'ustar'], ['browning', 'bes'], ['browning', 'fm'], ['browning', 'honors'], ['browning', 'hospital'], ['browning', 'smt'], ['browning', 'ustar'], ['fm', 'bes'], ['fm', 'browning'], ['fm', 'honors'], ['fm', 'hospital'], ['fm', 'smt'], ['fm', 'ustar'], ['honors', 'bes'], ['honors', 'browning'], ['honors', 'fm'], ['honors', 'hospital'], ['honors', 'smt'], ['honors', 'ustar'], ['hospital', 'bes'], ['hospital', 'browning'], ['hospital', 'fm'], ['hospital', 'honors'], ['hospital', 'smt'], ['hospital', 'ustar'], ['smt', 'bes'], ['smt', 'browning'], ['smt', 'fm'], ['smt', 'honors'], ['smt', 'hospital'], ['smt', 'ustar'], ['ustar', 'bes'], ['ustar', 'browning'], ['ustar', 'fm'], ['ustar', 'honors'], ['ustar', 'hospital'], ['ustar', 'smt']]


In [4]:
####################
# SETTING UP A     #
####################

A = np.zeros((len(links),2*len(rx_names)))

# delta is a vector of the sample number of the start of the sync in the recieved signal
link_num = 0
for link in links:
    # each link is a (tx_name, rx_name)
    tx_num = rx_names.index(link[0])
    rx_num = rx_names.index(link[1])
    A[link_num,tx_num] = 1
    A[link_num,len(rx_names)+tx_num] = 1
    A[link_num,rx_num] = -1
    A[link_num,len(rx_names)+tx_num]
    link_num += 1

print(" ----- A matrix ----- ")
print(A)

 ----- A matrix ----- 
[[ 1. -1.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 1.  0. -1.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0. -1.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0. -1.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0. -1.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0. -1.  1.  0.  0.  0.  0.  0.  0.]
 [-1.  1.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  1. -1.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  1.  0. -1.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0. -1.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0. -1.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0. -1.  0.  1.  0.  0.  0.  0.  0.]
 [-1.  0.  1.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0. -1.  1.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  1. -1.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  1.  0. -1.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0. -1.  0.  0.

In [5]:
####################
# FIND PEUSDO-INV  #
####################

pinvA = np.linalg.pinv(A)

print(" ----- peusdoinverse A ----- ")
print(pinvA)

 ----- peusdoinverse A ----- 
[[-3.18077812e-17 -5.36779536e-17  2.80562723e-17 -8.89892814e-18
   1.70084216e-17  3.20277980e-17 -1.42857143e-01  2.85714286e-02
   2.85714286e-02  2.85714286e-02  2.85714286e-02  2.85714286e-02
  -1.42857143e-01  2.85714286e-02  2.85714286e-02  2.85714286e-02
   2.85714286e-02  2.85714286e-02 -1.42857143e-01  2.85714286e-02
   2.85714286e-02  2.85714286e-02  2.85714286e-02  2.85714286e-02
  -1.42857143e-01  2.85714286e-02  2.85714286e-02  2.85714286e-02
   2.85714286e-02  2.85714286e-02 -1.42857143e-01  2.85714286e-02
   2.85714286e-02  2.85714286e-02  2.85714286e-02  2.85714286e-02
  -1.42857143e-01  2.85714286e-02  2.85714286e-02  2.85714286e-02
   2.85714286e-02  2.85714286e-02]
 [-1.42857143e-01  2.85714286e-02  2.85714286e-02  2.85714286e-02
   2.85714286e-02  2.85714286e-02 -3.90312782e-17  3.98986399e-17
   3.03576608e-17  1.90819582e-17 -1.56125113e-17 -9.97465999e-18
   2.85714286e-02 -1.42857143e-01  2.85714286e-02  2.85714286e-02
   2.857142

In [6]:
####################
# DELTA FOR REPNUM #
####################

col_num = 1
file_name = "col_" + str(col_num) + ".txt"
d = 0
delta = np.zeros((len(links),1))

with open(file_name,'r') as f:
    vals = f.readlines()
    
for val in vals:
    val = val.replace(",\n", "")
    delta[d] = (int(val))
    d += 1

print(" ----- delta vector from measurements ----- ")
print(delta)

 ----- delta vector from measurements ----- 
[[2725.]
 [3654.]
 [2733.]
 [2726.]
 [2726.]
 [2732.]
 [1820.]
 [2748.]
 [1811.]
 [1812.]
 [1812.]
 [1811.]
 [ 965.]
 [ 965.]
 [ 957.]
 [ 966.]
 [ 966.]
 [ 965.]
 [1949.]
 [1957.]
 [2886.]
 [1957.]
 [1949.]
 [1949.]
 [ 953.]
 [ 952.]
 [1889.]
 [ 951.]
 [ 960.]
 [ 951.]
 [1200.]
 [1200.]
 [2128.]
 [1208.]
 [1199.]
 [1199.]
 [2381.]
 [2373.]
 [3302.]
 [2373.]
 [2373.]
 [2382.]]


In [7]:
####################
# A MULTIPLICATION #
####################

estimate = np.dot(pinvA, delta)

print("Output of Shape: " + str(estimate.shape) + '\n')
print(" ----- estimate vector ----- ")
print(estimate)

Output of Shape: (14, 1)

 ----- estimate vector ----- 
[[ 131.74285714]
 [ 133.4       ]
 [-797.45714286]
 [ 133.42857143]
 [ 133.17142857]
 [ 131.74285714]
 [ 133.97142857]
 [2728.96666667]
 [1813.36666667]
 [1894.36666667]
 [1952.16666667]
 [ 953.96666667]
 [1201.96666667]
 [2374.36666667]]


In [8]:
####################
# GETTING ESTIMATE #
####################

e_est = estimate[:len(rx_names)]
T_est = estimate[len(rx_names):]

print(" ----- e_estimate ----- ")
print(e_est)
print(" ----- T_estimate ----- ")
print(T_est)

 ----- e_estimate ----- 
[[ 131.74285714]
 [ 133.4       ]
 [-797.45714286]
 [ 133.42857143]
 [ 133.17142857]
 [ 131.74285714]
 [ 133.97142857]]
 ----- T_estimate ----- 
[[2728.96666667]
 [1813.36666667]
 [1894.36666667]
 [1952.16666667]
 [ 953.96666667]
 [1201.96666667]
 [2374.36666667]]


In [9]:
####################
# PRINTING RESULTS #
####################

print(" ---------- column (repNum) 1 in delta.txt ---------- ")
print(Fore.RED + "(~, rx_name ) -----    e_estimate    -----   T_estimate" + Style.RESET_ALL)
r = 0

for rx in rx_names:
    rx_temp = rx
    if len(rx) != len("browning"):
        for i in range(len("browning")-len(rx)):
            rx_temp += " "
    if e_est[r][0] < 0 or T_est[r][0] < 0:
        print("(~, " + rx_temp + ") -----  [" + format(e_est[r][0],'.7f') + "]  ----- [" + 
              format(T_est[r][0],'.7f') + ']')
    else:
        print("(~, " + rx_temp + ") -----  [" + format(e_est[r][0],'.8f') + "]  ----- [" + 
              format(T_est[r][0],'.8f') + ']')
    r += 1

 ---------- column (repNum) 1 in delta.txt ---------- 
(~, rx_name ) -----    e_estimate    -----   T_estimate
(~, bes     ) -----  [131.74285714]  ----- [2728.96666667]
(~, browning) -----  [133.40000000]  ----- [1813.36666667]
(~, fm      ) -----  [-797.4571429]  ----- [1894.3666667]
(~, honors  ) -----  [133.42857143]  ----- [1952.16666667]
(~, hospital) -----  [133.17142857]  ----- [953.96666667]
(~, smt     ) -----  [131.74285714]  ----- [1201.96666667]
(~, ustar   ) -----  [133.97142857]  ----- [2374.36666667]


In [10]:
####################
# RUNNING ALL COLS #
####################

e_est_1, T_est_1 = find_e_vector(1,links)
e_est_2, T_est_2 = find_e_vector(2,links)
e_est_3, T_est_3 = find_e_vector(3,links)
e_est_4, T_est_4 = find_e_vector(4,links)

In [11]:
####################
# PRINTING COLS    #
####################

print_results(1, rx_names, e_est_1, T_est_1)
print('\n ------------------------------ \n')

print_results(2, rx_names, e_est_2, T_est_2)
print('\n ------------------------------ \n')

print_results(3, rx_names, e_est_3, T_est_3)
print('\n ------------------------------ \n')

print_results(4, rx_names, e_est_4, T_est_4)
print('\n ------------------------------ \n')

 ---------- column (repNum) 1 in delta.txt ---------- 
(~, rx_name ) -----    e_estimate    -----   T_estimate
(~, bes     ) -----  [131.74285714]  ----- [2728.96666667]
(~, browning) -----  [133.40000000]  ----- [1813.36666667]
(~, fm      ) -----  [-797.4571429]  ----- [1894.3666667]
(~, honors  ) -----  [133.42857143]  ----- [1952.16666667]
(~, hospital) -----  [133.17142857]  ----- [953.96666667]
(~, smt     ) -----  [131.74285714]  ----- [1201.96666667]
(~, ustar   ) -----  [133.97142857]  ----- [2374.36666667]

 ------------------------------ 

 ---------- column (repNum) 2 in delta.txt ---------- 
(~, rx_name ) -----    e_estimate    -----   T_estimate
(~, bes     ) -----  [16.34285714]  ----- [3071.76666667]
(~, browning) -----  [16.34285714]  ----- [2160.76666667]
(~, fm      ) -----  [-214.9428571]  ----- [3886.7666667]
(~, honors  ) -----  [19.22857143]  ----- [2294.56666667]
(~, hospital) -----  [14.60000000]  ----- [1302.96666667]
(~, smt     ) -----  [131.08571429]  -----